name: Update GTFS

on:
  schedule:
    - cron: "30 3 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Download GTFS files
      run: |
        mkdir -p gtfs-data/raw

        curl -L https://trinmo.org/gtfs-data/static/routes \
        -o gtfs-data/raw/routes.json

        curl -L https://trinmo.org/gtfs-data/stops \
        -o gtfs-data/raw/stops.json

        curl -L https://trinmo.org/gtfs-data/static/trips \
        -o gtfs-data/raw/trips.json


    - name: Commit files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add gtfs-data/raw

        git commit -m "Update GTFS data" || exit 0

        git push
