name: Update GTFS data

on:
  workflow_dispatch:

  schedule:
    - cron: "30 6 * * *"

permissions:
  contents: write


jobs:
  update-gtfs:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Create GTFS folder
        run: |
          mkdir -p gtfs-data


      - name: Download routes
        run: |
          curl -L "https://trinmo.org/gtfs-data/static/routes" \
          -o gtfs-data/routes.json


      - name: Download trips
        run: |
          curl -L "https://trinmo.org/gtfs-data/static/trips" \
          -o gtfs-data/trips.json


      - name: Download stops
        run: |
          curl -L "https://trinmo.org/gtfs-data/stops" \
          -o gtfs-data/stops.json


      - name: Download stop times
        run: |
          curl -L "https://trinmo.org/gtfs-data/static/stop_times" \
          -o gtfs-data/stop_times.json


      - name: Check downloaded files
        run: |
          ls -lh gtfs-data


      - name: Commit GTFS updates
        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"

          git add gtfs-data

          git commit -m "Update GTFS data" || echo "No changes to commit"


      - name: Push changes
        run: |
          git push
